improved import-export view (#28)
michal367/OI-Project pull request #120
Opened 2021-04-18 18:12 UTC by Petros9

Import/export view functionalities have been added

2021-04-18 19:05 UTC, ostatni5 requested changes
Please format your code before PR.

2021-04-18 19:05 UTC, ostatni5 commented on src/lecturer/components/questionsListView/QuestionsListView.tsx
> +    const onChangeImport = (event:any) => {
Please use proper type not `any`

2021-04-18 19:05 UTC, ostatni5 commented on src/lecturer/components/questionsListView/QuestionsListView.tsx
>          for (var i = 0, f; f = files[i]; i++) {
This loop is endless? 
It has assignment instead of conditional expression. ` f = files[i]`

2021-04-18 19:05 UTC, ostatni5 commented on src/lecturer/components/questionsListView/QuestionsListView.tsx
> +            <Input accept=".json" id="contained-button-file" type="file"onChange={(e) => onChangeImport(e)} />
<Input accept=".json" id="contained-button-file" type=**"file"onChange**={(e) => onChangeImport(e)} />
Add space between.

2021-04-18 19:26 UTC, Petros9 commented on src/lecturer/components/questionsListView/QuestionsListView.tsx
> +            <Input accept=".json" id="contained-button-file" type="file"onChange={(e) => onChangeImport(e)} />
ok

2021-04-18 19:49 UTC, Petros9 commented on src/lecturer/components/questionsListView/QuestionsListView.tsx
> +    const onChangeImport = (event:any) => {
I have fixed it

2021-04-18 19:55 UTC, ostatni5 requested changes

2021-04-18 19:55 UTC, ostatni5 commented on src/lecturer/components/questionsListView/QuestionsListView.tsx
> +            var f = files[0];
what if `files == []`?

2021-04-18 19:56 UTC, Petros9 commented on src/lecturer/components/questionsListView/QuestionsListView.tsx
> +            var f = files[0];
then error appears

2021-04-18 20:35 UTC, ostatni5 approved these changes
![obraz](https://i.pinimg.com/originals/29/2c/4b/292c4b31c724199c76455376c5018f9e.gif)

2021-04-19 14:08 UTC, michal367 approved these changes
Ok

2021-04-19 14:08 UTC, merged