unify types and fix some warnings (#223)
michal367/OI-Project pull request #269
Opened 2021-05-15 17:47 UTC by ostatni5

2021-05-15 20:30 UTC, michal367 approved these changes
Great

2021-05-16 11:53 UTC, Derstilon requested changes

2021-05-16 11:53 UTC, Derstilon commented on src/lecturer/components/reactionReceiveView/ReactionCounter.tsx
> -    }, [store.reactionValues[props.index]]);
The animation now plays for every reaction. Before it was only for the one that changed :/
![image](https://user-images.githubusercontent.com/26445545/118396088-16228f00-b64e-11eb-8ff9-eec06eade635.png)

2021-05-16 11:56 UTC, ostatni5 commented on src/lecturer/components/reactionReceiveView/ReactionCounter.tsx
> +    }, [props.index, store.reactionValues]);
```suggestion
    }, [store.reactionValues[props.index]]);
```

2021-05-16 12:03 UTC, Derstilon approved these changes
Works just fine

2021-05-16 12:15 UTC, merged