Send quiz functionality
michal367/OI-Project pull request #271
Opened 2021-05-16 13:08 UTC by rozchlastywacz

@Karolk99 code changes are needed

closes #225 if fixed

2021-05-16 18:24 UTC, Petros9 approved these changes
good job, how did you enhanced the answer type?

2021-05-24 13:35 UTC, Derstilon commented on src/student/components/quizView/QuestionsList.tsx
> +    const store = useContext(StoreContext);
```suggestion
```
Store is no longer used in this component

2021-05-24 13:45 UTC, Derstilon reviewed
Everything works for me. Let me know when the student side will be finished to approve or if those changes will come later in another PR

2021-05-29 22:03 UTC, Derstilon approved these changes
Conflicts were explosive
![image](https://media.tenor.com/images/b62a1eb41cbb13080484196877d54a14/tenor.gif)

2021-06-06 11:13 UTC, ostatni5 requested changes
The timer is not connected to the received quiz 

![obraz](https://user-images.githubusercontent.com/26521377/120922336-d721af80-c6c8-11eb-862d-42b708dfba88.png)
![obraz](https://user-images.githubusercontent.com/26521377/120922357-f3255100-c6c8-11eb-81d8-f3a96a52f8bd.png)

2021-06-06 11:13 UTC, ostatni5 commented on src/lecturer/components/sendQuizView/SendQuizView.tsx
> +
too many empty lines

2021-06-08 18:22 UTC, ostatni5 approved these changes

2021-06-08 18:31 UTC, merged