Send student question functionality
michal367/OI-Project pull request #275
Opened 2021-05-16 16:46 UTC by rozchlastywacz

sending questions works properly, but are added four times instead of one

closes #228 if #274 fixed

2021-05-16 18:23 UTC, Petros9 approved these changes
seems alright to me

2021-05-17 17:25 UTC, Derstilon commented on config-overrides.js
>  console.log("src dir:", src_dir);
Is this important?

2021-05-17 17:28 UTC, rozchlastywacz commented on config-overrides.js
>  console.log("src dir:", src_dir);
@ostatni5

2021-05-17 17:33 UTC, michal367 commented on config-overrides.js
>  console.log("src dir:", src_dir);
yes

2021-05-17 17:33 UTC, Derstilon requested changes
Please remove mock data if we won't use it anymore or at least fix the typo in the name
[mockData](https://github.com/michal367/OI-Project/blob/feature/connect-question-sending/src/lecturer/util/mockData.ts)

2021-05-17 20:23 UTC, Petros9 approved these changes

2021-05-17 20:26 UTC, Derstilon approved these changes

2021-05-17 20:28 UTC, michal367 approved these changes

2021-05-17 20:52 UTC, merged