Block creating same quizes and questions
michal367/OI-Project pull request #286
Opened 2021-05-17 20:41 UTC by Karolk99

działa

2021-05-18 16:07 UTC, michal367 requested changes

2021-05-18 16:07 UTC, michal367 commented on src/lecturer/components/createQuestionView/CreateQuestionView.tsx
> +                temp.title = "Istnieje już pytanie z takim tytułem";
add break if title found. If you fix it you are ready to go.

2021-05-18 22:23 UTC, michal367 approved these changes

2021-05-19 08:34 UTC, Petros9 approved these changes
glorious

2021-05-25 18:33 UTC, merged