Add functionality without alert
michal367/OI-Project pull request #290
Opened 2021-05-19 08:07 UTC by Karolk99

![image](https://user-images.githubusercontent.com/56369082/118778058-03949980-b88a-11eb-8d09-c0c1320fbe40.png)

2021-05-19 08:11 UTC, Karolk99 commented
it is really easy to change the position of snackbar so don't be bothered

2021-05-19 10:46 UTC, michal367 requested changes
Questions with the same title should not be imported
Snackbar should be lower
Snackbar should dissapear after some time
Change "Importowano" to "Zaimportowano"
App breaks if I import empty file or json with different structure (e.g. {}) or file is not json

2021-05-24 13:46 UTC, Derstilon reviewed
Let me know when you will be done with @michal367's changes

2021-05-25 17:47 UTC, michal367 requested changes

2021-05-25 17:47 UTC, michal367 commented on src/lecturer/components/questionsListView/QuestionsListView.tsx
> +        />
```suggestion
        <Snackbar
            anchorOrigin={{ vertical, horizontal }}
            open={open}
            onClose={handleClose}
            message={message}
            key={vertical + horizontal}
            autoHideDuration={1000}
            style={{top: "60px"}}
        />
```

2021-05-25 17:54 UTC, michal367 approved these changes

2021-05-25 19:50 UTC, Derstilon approved these changes
Good job. Looks clean

2021-05-25 22:26 UTC, merged