improve student questions view (#284)(#276)
michal367/OI-Project pull request #300
Opened 2021-05-22 20:33 UTC by Petros9

the `Pytania od studentów` bar is added, the new question are now marked by red color 
![image](https://user-images.githubusercontent.com/58508596/119240065-c2cca700-bb4d-11eb-8e0a-2e0f064e221e.png)

2021-05-23 17:31 UTC, rozchlastywacz approved these changes
![200](https://user-images.githubusercontent.com/44035398/119270548-7b9def00-bbfd-11eb-8325-bff8b522b3b2.gif)

2021-05-23 20:56 UTC, Derstilon commented on src/lecturer/components/notifiableTab/NotifiableTab.tsx
> +    const resetFunction = props.resetFunction?? nothing;
```suggestion
    const [notifiableNumber, setNotifiableNumber] = useState(0);
    const label = props.label ?? "none";
    const routes = props.routes ?? "";
    const value = props.value ?? "";
    const resetFunction = props.resetFunction ?? (() =>{ });
```
This is much cleaner

2021-05-23 20:57 UTC, Derstilon commented on src/lecturer/components/notifiableTab/NotifiableTab.tsx
>      const value = props.value ?? "";
You don't use `value` anywhere in this component

2021-05-23 21:04 UTC, Derstilon commented on src/lecturer/components/studentsQuestionView/StudentsQuestionListView.tsx
> +                            )}
```suggestion
                                <TextField className={classes.field} error={!studentQuestion.processed} variant="outlined"
                                 fullWidth={true} 
                                 multiline
                                 label={studentQuestion.time.toLocaleTimeString("en-GB") + " | Anonimowy student"} 
                                 defaultValue={studentQuestion.text} InputProps={{
                                    className: classes.questionText,
                                    readOnly: true,
                                }}/>
```
You could remove this duplicating code by moving "if" statement into the  "error" property

2021-05-23 21:08 UTC, Derstilon requested changes
I've added some code refactor suggestions and new issues for the bugs I've seen. #304 #305  Please add those changes, write a description for those tasks for future reference and let me know when you'll be done so that I can approve PR.

2021-05-25 13:48 UTC, Derstilon approved these changes

2021-05-25 14:05 UTC, merged