Fix/store session and visual bug + reaction final features
michal367/OI-Project pull request #337
Opened 2021-05-27 22:55 UTC by Derstilon

![image](https://user-images.githubusercontent.com/26445545/119906422-7cf94f80-bf4e-11eb-9a3c-89acefca6b6a.png)
I've added a progress bar over the reactions buttons.
Fixed an issue that reactions didn't clear after changing the mode.
Added store cleanup operation.
Fixed routing bug.
Added back topbar underline and enhanced the code for future routing.
Enhanced mockup code for better development experience.

2021-05-28 11:01 UTC, ostatni5 requested changes
A session is created but the view does not change.

![obraz](https://user-images.githubusercontent.com/26521377/119974281-bfee0e00-bfb4-11eb-981b-a41309a5a34a.png)
![obraz](https://user-images.githubusercontent.com/26521377/119974302-c7adb280-bfb4-11eb-8311-acf0e0992489.png)
![obraz](https://user-images.githubusercontent.com/26521377/119974335-cda39380-bfb4-11eb-9e80-e21ab3d9d4de.png)

2021-05-28 11:02 UTC, michal367 requested changes
Lecturer homepage doesn't work on HTTP deno server (after clicking in menu I can go to homepage) - it is for sure problem with front routing
When I start session I am not redirected to session page (it only appears at first visit at website - maybe localstorage problem?)

When I refresh website I am still redirected to random page (not as many times as before but still it happens). Take a look at url. It still wanders between sites.

Reaction timer is starting even when students use only marked by lecturer reactions
After refreshing website marked reactions dissapear (is it intended?)
I think reactions progressbar should be more smooth

I think there should be no starting mock in questions

2021-05-28 11:03 UTC, michal367 commented on src/lecturer/components/sessionDashboardView/SessionDashboardView.tsx
> -    // }, [handleGetStudentList, sendJsonMessage, socketEmiter]);
Why did you remove it? @rozchlastywacz told me it should stay for later.

2021-05-29 19:21 UTC, michal367 approved these changes
Great job

![obraz](https://user-images.githubusercontent.com/24357718/120082514-c4551c80-c0c3-11eb-8380-bd73f9b6e0a1.png)

2021-05-30 11:00 UTC, ostatni5 reviewed
It works ok.

2021-05-30 11:00 UTC, ostatni5 commented on server/server.ts
> +            }else if (ctx.request.url.pathname.startsWith("/student/"))
Empty if body?

2021-05-30 11:00 UTC, ostatni5 commented on src/common/util/routeToTabsValue.ts
> +}
This file is only useful for the lecturer move to lecturer/util or event better to folder connected with routing

2021-05-30 11:00 UTC, ostatni5 commented on src/student/components/joinSessionView/JoinSessionView.tsx
> +        let sessionId = "";
Why not use a consistent style when naming variables like camelCase?

2021-05-30 14:50 UTC, Derstilon commented on src/common/util/routeToTabsValue.ts
> +}
![image](https://user-images.githubusercontent.com/26445545/120108831-2155de80-c167-11eb-9b6b-6374ca80d555.png)
new path

2021-05-30 14:57 UTC, Derstilon commented on src/student/components/joinSessionView/JoinSessionView.tsx
> +        let sessionId = "";
To be fair this isn't id for the session, but an invitation code. I've changed it accordingly.

2021-05-30 16:19 UTC, ostatni5 commented on src/student/components/joinSessionView/JoinSessionView.tsx
> +        let sessionId = "";
XD

2021-05-30 16:24 UTC, ostatni5 approved these changes
PR with too many changes, it is hard to analyze code.

2021-05-30 19:13 UTC, merged