enable PWA for student app (#332)(#333)
michal367/OI-Project pull request #340
Opened 2021-05-29 15:38 UTC by ostatni5

enable PWA for student
split public folder

2021-05-30 02:09 UTC, michal367 requested changes
make public_dir to be loaded as 3rd arg (`process.argv[3]`) and build_dir be 4th
make public_dir like src_dir
in the end build command should work like this:
`react-app-rewired build src/lecturer public/lecturer build/lecturer`
(don't forget about another commands like start)

`set PUBLIC_URL=/lecturer` may not work on heroku (windows instruction)
instead of using PUBLIC_URL var just use name of folder in index.html, for example: 
`/student/manifest.json`

delete all those comments from index.html

app on firefox and chrome have different names. one browser gets name from manifest.json, second browser gets from title
long name of app in manifest.json - barely fit on screen
![obraz](https://user-images.githubusercontent.com/24357718/120089662-bc659e80-c0fc-11eb-91b5-ab39648ae643.png)

2021-05-30 02:13 UTC, michal367 commented on public/student/robots.txt
> +# https://www.robotstxt.org/robotstxt.html
remove

2021-05-31 12:24 UTC, ostatni5 commented on public/student/robots.txt
> +# https://www.robotstxt.org/robotstxt.html
i dont see why i should

2021-05-31 16:52 UTC, michal367 approved these changes

2021-05-31 16:59 UTC, michal367 commented on public/student/index.html
> +    <link rel="icon" href="/student/favicon.ico" />
```suggestion
    <link rel="icon" href="/student/favicon.ico" />
    <!-- Favicon Author 
    © 2016 - 2021 PNG All.
    https://creativecommons.org/licenses/by-nc/4.0/
    http://www.pngall.com/lecture-png/download/42561 -->
```

2021-05-31 16:59 UTC, michal367 commented on public/lecturer/index.html
> +    <link rel="icon" href="/lecturer/favicon.ico" />
```suggestion
    <link rel="icon" href="/lecturer/favicon.ico" />
    <!-- Favicon Author 
    © 2016 - 2021 PNG All.
    https://creativecommons.org/licenses/by-nc/4.0/
    http://www.pngall.com/lecture-png/download/42561 -->
```

2021-06-02 09:50 UTC, rozchlastywacz approved these changes
10/10

2021-06-06 10:48 UTC, merged