Fix quiz import and also small change to question import
michal367/OI-Project pull request #352
Opened 2021-05-31 12:26 UTC by Karolk99

2021-05-31 23:01 UTC, michal367 requested changes
separate checking functions (`isQuestionCorrect`, `isQuizCorrect` - they should check if given question/quiz is correct and return true/false) from those importing functions and place them in some file in `lecturer/util` folder

I can import quiz without questions (empty questions array) and I should not

2021-05-31 23:01 UTC, michal367 commented on src/lecturer/components/quizzesListView/QuizzesListView.tsx
> +        console.log("start");
remove console.log

2021-05-31 23:01 UTC, michal367 commented on src/lecturer/components/quizzesListView/QuizzesListView.tsx
> +            console.log("end");
remove

2021-06-08 21:27 UTC, Petros9 approved these changes
good

2021-06-09 00:22 UTC, michal367 approved these changes

2021-06-09 00:24 UTC, merged