Add enter functionality to lecturer
michal367/OI-Project pull request #354
Opened 2021-05-31 15:39 UTC by Karolk99

2021-06-04 12:30 UTC, Derstilon requested changes
One small change and you're good to go. Good job :)

2021-06-04 12:30 UTC, Derstilon commented on src/lecturer/components/createQuestionView/CreateQuestionView.tsx
> +import { ChangeEvent, FormEvent, useCallback, useContext, useEffect, useRef, useState } from 'react';
```suggestion
import { ChangeEvent, useCallback, useContext, useEffect, useRef, useState } from 'react';
```
You've removed usage of `FormEvent` from line 276 so you should delete import as well

2021-06-08 20:45 UTC, Derstilon approved these changes

2021-06-08 23:26 UTC, michal367 approved these changes

2021-06-08 23:38 UTC, merged