Feature/better animation student reaction
michal367/OI-Project pull request #369
Opened 2021-06-08 23:09 UTC by ostatni5

2021-06-08 23:12 UTC, Petros9 requested changes
the rest seems alright

2021-06-08 23:12 UTC, Petros9 commented on src/lecturer/components/quizStatsView/QuestionBlock.tsx
> +
unnecessary change

2021-06-08 23:50 UTC, ostatni5 commented on src/lecturer/components/quizStatsView/QuestionBlock.tsx
> +
enter is necessary

2021-06-08 23:56 UTC, rozchlastywacz commented on src/lecturer/components/quizStatsView/QuestionBlock.tsx
> +
![image](https://user-images.githubusercontent.com/44035398/121272293-e0c43680-c8c5-11eb-9784-c9f3bdb1610b.png)

2021-06-08 23:56 UTC, rozchlastywacz approved these changes
gg wp

2021-06-09 00:13 UTC, Petros9 approved these changes
glorious

2021-06-09 00:52 UTC, merged